PACKAGE OBJECTSNEU;

IMPORT JAVA.IO.FILE;

PUBLIC CLASS CINHALTDIR {

	PUBLIC STATIC VOID MAIN(STRING[] ARGS) {
		// TODO AUTO-GENERATED METHOD STUB
		FILE FILE = NEW FILE("C:\\TEMP");
		IF (FILE.ISDIRECTORY())
		{
			STRING[] INHALT = FILE.LIST()
;
			FOR (INT I=0; I<INHALT.LENGTH; I++)
				SYSTEM.OUT.PRINTLN(INHALT[I]);
			}
	}

}
